name: millenium
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1 
  firebase_auth: ^0.15.3
  flutter_launcher_icons: "^0.7.3"
  uuid: 2.0.1
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  json_annotation: ^3.0.0
  image_picker: ^0.6.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  json_serializable: ^3.2.3
  build_runner: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  fonts:
    - family: pentagrams_malefissent
      fonts:
        - asset: assets/fonts/pentagrams_malefissent.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
